apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-forecast-2
  description: Weather Forecast with annotations/new field
  has-rfc: true
  annotations:
    backstage.io/view-url: https://some.website/catalog-info.yaml
    backstage.io/edit-url: https://github.com/my-org/catalog/edit/master/my-service.jsonnet
    has-rfc3: "true"
spec:
  type: service
  lifecycle: experimental
  owner: team-a
